# theme: minima
lang: en-US
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
title: Hope This Helps
author: Matt Burnett
description: Notes to self and related infos. Don''t expect anything profound.
url: https://mattburnett-repo.github.io/blog/
logo: /assets/ladderIcon_01.png
github_username: mattburnett-repo
