# theme: minima
lang: en-US
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
title: Hope This Helps
author: Matt Burnett
description: Notes to self and related infos. Don''t expect anything profound.
url: https://mattburnett-repo.github.io/blog/
logo: /assets/ladderIcon_01.png
github_username: mattburnett-repo

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
      alt_title: "Hope This Helps"
      sub_title: "The name says it all"
      introduction: |
        Basically Basic is a Jekyll theme meant to be a substitute for the default --- [Minima](https://github.com/jekyll/minima). Conventions and features found in Minima are fully supported by **Basically Basic**.
      actions:
        - label: "Learn More"
          icon: github
          url: "http://url-goes-here.com"
        - label: "Download"
          icon: download
          url: "http://url-goes-here.com"
      image: /assets/linkedInBannerImage.png
      author:
        name: John Doe
        twitter: johndoetwitter
      comments: false

